version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: app

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    environment:
      MONGODB_URI: mongodb://app:app@mongo:27017/app?authSource=admin
